### ISSUE TITLE
running is error

### ISSUE THREAD

**Issue by jwh5566** [atlantos/nagios-check-gluster#13]
hello! thanks for the script.
I installed the ruby , but when i run the script,it says "no such file to load -- rubygems"
like below, how could i resolve the problem, please reply soon. thanks a lot.

[root@nagios-check-gluster]# ./check_gluster.rb -h
no such file to load -- rubygems

**Comment by atlantos** [comment]
It's not this code issue. You need to make sure that ruby gems package is installed. On  CentOS it can be done as ```yum install rubygems```
