### ISSUE TITLE
Cannot Run this script with "nagios" user

### ISSUE THREAD

**Issue by Wayne-Wen** [atlantos/nagios-check-gluster#8]
I am trying to run this script with "nagios" user, who running the icinga2. But it is failed: 
`Error: Operation not permitted`
Here is how I test it:
`su - nagios -s /bin/bash`
`/usr/lib/nagios/plugins/check_gluster -h`
I got the "Usage" information. 
`/usr/lib/nagios/plugins/check_gluster`
I got the `Error: Operation not permitted`

**Comment by agit05** [comment]
Try to add nagios privileged permissions.
Add:
nagios          ALL=NOPASSWD: /usr/lib/nagios/plugins/check_gluster

To either /etc/sudoers.d/nrpe or /etc/sudoers

**Comment by atlantos** [comment]
According to https://github.com/atlantos/nagios-check-gluster:

```
It requires root privileges.
```
